### PR TITLE
#2 ETNA-756

### PR DESCRIPTION
**Pull request by Mr-Geekman**
Added `BaseMixin` with method `__repr__` and tests for it.

### CODE REVIEW

**Comment by imitskovets** [comment]
I think we should create library issues on github. So any contributor would be able to review PR's

**Comment by martins0n** [comment]
```
>>> from etna.transforms.lags import LagTransform
>>> lags = LagTransform(in_column="target", lags=list(range(8, 24, 1)))
>>> lags
LagTransform(lags = None, in_column = None, )
```
We should save input arguments additionaly for classes which are inherited from wrappers like `PerSegmentWrapper`

**Review by martins0n — CHANGES_REQUESTED** [review]
```
>>> from etna.transforms.lags import LagTransform
>>> lags = LagTransform(in_column="target", lags=list(range(8, 24, 1)))
>>> lags
LagTransform(lags = None, in_column = None, )
```
We should save input arguments additionaly for classes which are inherited from wrappers like `PerSegmentWrapper` and persegmentmodels like prophet have the same issue.

**Review by martins0n — APPROVED** [review]
👍

**Pull request merged**
